name: swap
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  go_router: ^14.3.0
  flutter_svg: ^2.0.10+1
  flutter_riverpod: ^2.6.1
  google_maps_flutter: ^2.9.0
  location: ^7.0.1
  geolocator: ^13.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon/core/
    - assets/icon/root/
    - assets/image/core/
    - assets/image/home/
    - assets/image/place/
    - assets/image/purchase/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/font/pretendard_bold.otf
          weight: 700
        - asset: assets/font/pretendard_semibold.otf
          weight: 600
        - asset: assets/font/pretendard_regular.otf
          weight: 400
